# Generated by Django 3.2.4 on 2021-07-07 07:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0003_baibao_place_publication_restaurant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Python2104',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=150)),
                ('tuoi', models.IntegerField()),
                ('diachi', models.TextField()),
            ],
            options={
                'db_table': 'Python2104',
            },
        ),
        migrations.AlterField(
            model_name='reporter',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Địa chỉ Email'),
        ),
        migrations.AlterField(
            model_name='reporter',
            name='first_name',
            field=models.CharField(max_length=30, verbose_name='Tên'),
        ),
        migrations.AlterField(
            model_name='reporter',
            name='last_name',
            field=models.CharField(max_length=30, verbose_name='Họ'),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
