# Generated by Django 3.2.4 on 2021-07-09 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_abc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abc',
            name='publications',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='abc',
        ),
    ]
