# Generated by Django 3.2.4 on 2021-07-09 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_post'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='post',
            table='Post',
        ),
    ]
